from enum import Enum

class GaugeDefinitions(str, Enum):
    tempinc = "Indoor Temperature in Celsius"
    humidityin = "Indoor Humidity"
    baromrelhpa = "Relative Barometric Pressure in hPa"
    baromabshpa = "Absolute Barometric Pressure in hPa"
    tempc = "Outdoor Temperature in Celsius"
    humidity = "Outdoor Humidity"
    vpd = "Vapor Pressure Deficit"
    winddir = "Wind Direction in Degrees"
    winddir_avg10m = "10 Minute Average Wind Direction in Degrees"
    windspeedmph = "Wind Speed in Miles per Hour"
    windgustmph = "Wind Gust in Miles per Hour"
    maxdailygustmph = "Maximum Daily Wind Gust in Miles per Hour"
    solarradiation = "Solar Radiation in W/m²"
    uv = "UV Index"
    rainratein = "Rain Rate in Inches per Hour"
    eventrainin = "Event Rain in Inches"
    hourlyrainin = "Hourly Rain in Inches"
    last24hrainin = "Last 24 Hour Rain in Inches"
    dailyrainin = "Daily Rain in Inches"
    weeklyrainin = "Weekly Rain in Inches"
    monthlyrainin = "Monthly Rain in Inches"
    yearlyrainin = "Yearly Rain in Inches"
    totalrainin = "Total Rain in Inches"
    lightning_num = "Number of Lightning Strikes"
    lightning = "Distance to Nearest Lightning Strike in km"
    lightning_time  = "Time of last Lightning Strike"
